name: nagada_client
description: A client-side SDK for the Nagada Sync Protocol, enabling offline-first data synchronization for Dart and Flutter applications.
version: 0.1.0-experimental
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '^3.8.0'

dependencies:
  http: ^1.2.1
  uuid: ^4.4.0
  meta: ^1.12.0
  json_annotation: ^4.9.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.2
  mockito: ^5.4.4